Deps: Update faithfuls <easy-as-pypi>
- Source: easy-as-pypi @ 350aee09df60 [1.1.11a7~42]

- Commit generated by:

    https://github.com/thegittinsgood/git-update-faithful#⛲

  under the guidance of:

    https://github.com/doblabs/easy-as-pypi/blob/release/bin/update-faithful

diff --git a/.github/bin/wrangle-tags b/.github/bin/wrangle-tags
--- a/.github/bin/wrangle-tags
+++ b/.github/bin/wrangle-tags
@@ -57,6 +57,8 @@ EAPP_CI_TAG_INHIBIT_CASCADE="ci-inhibit-cascade"
 EAPP_CI_TAG_INHIBIT_FOREVER="ci-inhibit-forever"
 EAPP_CI_TAG_CASCADE_UPDATEDEPS="ci-cascade-updatedeps"
 EAPP_CI_TAG_CASCADE_VERSIONING="ci-cascade-versioning"
+EAPP_CI_TAG_INHIBIT_ALPHA="ci-inhibit-alpha"
+EAPP_CI_TAG_INHIBIT_PATCH="ci-inhibit-patch"
 
 # REFER: See ./.github/workflows/ci-tags-wrangle.yml for the 
 #        environs this script uses as runtime args. They all
@@ -66,6 +68,8 @@ EAPP_CI_TAG_CASCADE_VERSIONING="ci-cascade-versioning"
 #           EAPP_INHIBIT_FOREVER: ${{ inputs.inhibit-forever }}
 #           EAPP_CASCADE_UPDATEDEPS: ${{ inputs.cascade-updatedeps }}
 #           EAPP_CASCADE_VERSIONING: ${{ inputs.cascade-versioning }}
+#           EAPP_INHIBIT_ALPHA: ${{ inputs.inhibit-alpha }}
+#           EAPP_INHIBIT_PATCH: ${{ inputs.inhibit-patch }}
 #
 #        The corresponding delete tags each default false:
 #
@@ -73,6 +77,8 @@ EAPP_CI_TAG_CASCADE_VERSIONING="ci-cascade-versioning"
 #           EAPP_DELETE_INHIBIT_FOREVER: ${{ inputs.delete-inhibit-forever }}
 #           EAPP_DELETE_CASCADE_UPDATEDEPS: ${{ inputs.delete-cascade-updatedeps }}
 #           EAPP_DELETE_CASCADE_VERSIONING: ${{ inputs.delete-cascade-versioning }}
+#           EAPP_DELETE_INHIBIT_ALPHA: ${{ inputs.delete-inhibit-alpha }}
+#           EAPP_DELETE_INHIBIT_PATCH: ${{ inputs.delete-inhibit-patch }}
 
 # Optional special keyword, e.g., "FALSE", you could use to delete
 # tags, vs. using the EAPP_DELETE_* environs.
@@ -93,7 +99,8 @@ wrangle_tags () {
 
   trace_full
 
-  trace_lite "┌─ CI Wrangler: tag-name: ────┬─🥚─┬─ new-val: ─┬─ output-name and val: ────────────┐"
+  # USYNC: CI_tags_table_column_widths
+  trace_lite "┌─ CI Wrangler: tag-name: ───────────┬─🥚─┬─ new-val: ─┬─ output-name and val: ────────────┐"
 
   for which_tag in "${tag_names[@]}"; do
     trace_full "which tag: ${which_tag}"
@@ -120,7 +127,8 @@ wrangle_tags () {
     trace_full
   done
 
-  local footer_rhs="─────────────────────────────┴────┴────────────┴───────────────────────────────────┘"
+  # USYNC: CI_tags_table_column_widths
+  local footer_rhs="────────────────────────────────────┴────┴────────────┴───────────────────────────────────┘"
 
   local piping="└"
   if [ -n "${GIT_PUSH_OUTPUT_DUMP}" ] || [ -n "${GITHUB_OUTPUT}" ]; then
@@ -153,7 +161,7 @@ wrangle_tags () {
 # ***
 
 wrangle_tag () {
-  local tag_name="$1"
+  local tag_name_base="$1"
   local out_name="$2"
   local tag_scope="$3"
   local default_value="$4"
@@ -162,7 +170,7 @@ wrangle_tag () {
   local skip_if="$7"
 
   trace_full "manage-ci-tag @ $(git rev-parse HEAD)"
-  trace_full "- tag_name: ${tag_name}"
+  trace_full "- tag_name_base: ${tag_name_base}"
   trace_full "- out_name: ${out_name}"
   trace_full "- tag_scope: ${tag_scope}"
   trace_full "- default_value: ${default_value}"
@@ -178,36 +186,26 @@ wrangle_tag () {
 
   # ***
 
+  local branch_name="$(git rev-parse --abbrev-ref=loose HEAD)"
+
+  local tag_name
+  tag_name="$(format_tag_name "${tag_name_base}" "${tag_scope}" "${branch_name}")"
+
+  # ***
+
   local tag_exists=false
 
   if [ "${tag_scope}" = "HEAD" ]; then
-    # A "HEAD" tag is only valid if on HEAD commit.
-    # - This branch followed by all tags but 'ci-inhibit-forever'.
-    local head_tag_match="$(git tag --list --points-at HEAD "${tag_name}")"
-
-    if [ -n "${head_tag_match}" ]; then
+    if head_tag_found "${tag_name}"; then
       tag_exists=true
     fi
-  else
-    # A "branch" tag is valid if it's on any commit in the branch.
-    # - This code path followed by only the 'ci-inhibit-forever'
-    #   tag (for now, says 2023-11-22).
-
-    # Use not-fully-qualified branch name because refs/heads/<branch> doesn't
-    # work with git-branch (so not `git rev-parse --symbolic-full-name HEAD`).
-    local default_branch="$(git rev-parse --abbrev-ref=loose HEAD)"
-
-    # - The name pattern — ${default_branch} — is ^strict$ w/out wildcards.
-    # - If tag absent, dies: 'error: malformed object name refs/tags/foo'.
-    local branch_tag_match
-    if branch_tag_match="$(
-      git branch --list --contains "refs/tags/${tag_name}" "${default_branch}" \
-        2> /dev/null
-    )"; then
-
-      if [ -n "${branch_tag_match}" ]; then
-        tag_exists=true
-      fi
+  elif [ "${tag_scope}" = "branch" ]; then
+    if branch_tag_found "${tag_name}" "${branch_name}"; then
+      tag_exists=true
+    fi
+  elif [ "${tag_scope}" = "project" ]; then
+    if project_tag_found "${tag_name}"; then
+      tag_exists=true
     fi
   fi
 
@@ -232,21 +230,23 @@ wrangle_tag () {
     # - But always delete HEAD-only tag, in
     #   case stale one persists elsewhere.
     if ${tag_exists} || [ "${tag_scope}" = "HEAD" ]; then
-      git tag -d "${tag_name}" 2> /dev/null || true
+      git tag -d "${tag_name}" \
+        > "${GIT_PUSH_OUTPUT_DUMP}" 2>&1 || true
 
       if ${CI:-false}; then
         git push "${EAPP_CI_REMOTE_NAME}" ":refs/tags/${tag_name}" \
-          > "${GIT_PUSH_OUTPUT_DUMP}"
+          > "${GIT_PUSH_OUTPUT_DUMP}" 2>&1
       fi
     fi
   elif [ -n "${new_tag_value}" ]; then
     # Create tag if new value not non-empty and not "false".
     if ! ${tag_exists}; then
-      git tag -f -a "${tag_name}" -m "${new_tag_value}"
+      git tag -f -a "${tag_name}" -m "${new_tag_value}" \
+        > "${GIT_PUSH_OUTPUT_DUMP}" 2>&1
 
       if ${CI:-false}; then
         git push -f "${EAPP_CI_REMOTE_NAME}" "refs/tags/${tag_name}" \
-          > "${GIT_PUSH_OUTPUT_DUMP}"
+          > "${GIT_PUSH_OUTPUT_DUMP}" 2>&1
       fi
     fi
   fi
@@ -255,8 +255,9 @@ wrangle_tag () {
 
   trace_full "${out_name}: ${old_tag_value}"
 
+  # USYNC: CI_tags_table_column_widths
   trace_lite \
-    "├── $(printf '%-25s' "${tag_name}")" \
+    "├── $(printf '%-32s' "${tag_name}")" \
     "│  $(${tag_exists} && echo ✓ || echo ✗)" \
     "│ $(printf '%+10s' "${new_tag_value}")" \
     "│ $(printf '%-27s' "${out_name}:") $(printf '%-5s' "${old_tag_value}") │"
@@ -265,6 +266,119 @@ wrangle_tag () {
     # Aka `if ${CI:-false}; then`.
     echo "${out_name}=${old_tag_value}" >> "${GITHUB_OUTPUT}"
   fi
+}
+
+# ***
+
+# Mung the tag_name depending on tag_scope.
+
+format_tag_name () {
+  local tag_name_base="$1"
+  local tag_scope="$2"
+  local branch_name="$3"
+
+  # - First, strip the 'ci-' prefix from the tag name.
+  local tag_name_raw="$(echo "${tag_name_base}" | sed 's/^ci-//')"
+
+  # - Next form the proper tag name for the given scope.
+  local tag_name="${tag_name_base}"
+
+  if false \
+    || [ "${tag_scope}" = "HEAD" ] \
+    || [ "${tag_scope}" = "branch" ] \
+  ; then
+    # Convert, 'ci-{postfix}' → 'ci-{branch_name}-{postfix}'
+    tag_name="ci-${branch_name}-${tag_name_raw}"
+  elif [ "${tag_scope}" != "project" ]; then
+    # "project" tags are unmunged, but if scope var
+    # says something unknown, that's a dev error.
+    >&2 echo "GAFFE: Unknown tag_scope: ${tag_scope}"
+
+    exit 1
+  fi
+
+  trace_full "- branch_name: ${branch_name}"
+  trace_full "- tag_name: ${tag_name}"
+
+  printf "%s" "${tag_name}"
+}
+
+# ***
+
+# A "HEAD" tag is only valid if on HEAD commit.
+# - This branch followed by all tags but 'ci-inhibit-forever'.
+
+head_tag_found () {
+  local tag_name="$1"
+
+  local head_tag_match="$(git tag --list --points-at HEAD "${tag_name}")"
+
+  [ -n "${head_tag_match}" ]
+}
+
+# A "branch" tag is valid if it's on any commit in the branch.
+# - This code path followed by only the 'ci-inhibit-forever'
+#   tag (for now, says 2023-11-22).
+
+branch_tag_found () {
+  local tag_name="$1"
+  local branch_name="$2"
+
+  local tag_exists=false
+
+  local try_it_the_hard_way=true
+  local try_it_the_easy_way=true  # Or so I'm led to believe
+
+  local branch_tag_match=""
+  local merged_tag_match=""
+
+  [ -n "${tag_name}" ] \
+    || return 1
+
+  if ${try_it_the_hard_way}; then
+    # - The name pattern — ${branch_name} — is ^strict$ w/out wildcards.
+    # - If tag absent, dies: 'error: malformed object name refs/tags/foo'.
+    # - Note this must uses not-fully-qualified branch name (e.g., 'main')
+    #   because refs/heads/<branch> does not work with git-branch (so not
+    #   `git rev-parse --symbolic-full-name HEAD`).
+    branch_tag_match="$(
+      git branch --list --contains "refs/tags/${tag_name}" "${branch_name}" \
+        2> /dev/null
+    )" || true
+  fi
+
+  if ${try_it_the_easy_way}; then
+    # Apparently I didn't read man git-log close enough when I wrote
+    # this code the hard way.
+    merged_tag_match="$(git tag --list --merged HEAD "${tag_name}")"
+  fi
+
+  # Check that you didn't wreck yourself.
+  if true \
+    && ${try_it_the_hard_way} \
+    && ${try_it_the_easy_way} \
+    && [ "${branch_tag_match}" != "${merged_tag_match}" ] \
+  ; then
+    >&2 echo "GAFFE: branch tag sniffers disagree:"
+    >&2 echo "- branch_tag_match: ${branch_tag_match}"
+    >&2 echo "- merged_tag_match: ${merged_tag_match}"
+    >&2 echo "For tag “${tag_nama}” on branch “${branch_name}”"
+
+    exit 1
+  fi
+
+  [ -n "${branch_tag_match}" ] || [ -n "${merged_tag_match}" ]
+}
+
+# A "project" tag is hot if its on any commit,
+# i.e., if it exists.
+
+project_tag_found () {
+  local tag_name="$1"
+
+  local any_tag_match="$(git tag --list "${tag_name}")"
+
+  [ -n "${any_tag_match}" ]
 }
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
@@ -296,6 +410,10 @@ set_tag_locals () {
 
   set_tag_locals_cascade_versioning
 
+  set_tag_locals_inhibit_alpha
+
+  set_tag_locals_inhibit_patch
+
   # ***
 
   tag_name="${which_tag}"
@@ -309,19 +427,24 @@ is_this_tag_object_specified () {
   trace_full "which_tag: ${which_tag}"
   trace_full "tag_name: ${tag_name}"
 
-  # Sometimes, initially, workflows call with which_tag unset,
-  # and we procure a list of all tag names.
+  # This is a little hacky, but it lets us use 'local' vars like an object:
+  #
+  # On the first call to set_tag_locals, the script compiles the list
+  # of all tag names (which are defined below in the separate fcns).
   [ -n "${which_tag}" ] || tag_names+=("${tag_name}")
 
-  # Other times, workflows specify the tag name, and we'll use
-  # `local` vars. to return values for that tag.
+  # On the second call to set_tag_locals, the script wants us to set
+  # the local vars. for a specific tag.
+  #
+  # In this manner we use 'local' vars. in lieu of object, or even
+  # decent associative array support in (Ba)sh.
   [ -n "${which_tag}" ] && [ "${which_tag}" = "${tag_name}" ]
 }
 
 # ***
 
 set_tag_locals_inhibit_cascade () {
-  # E.g., "ci-inhibit-cascade"
+  # E.g., "ci-{branch}-inhibit-cascade"
   tag_name="${EAPP_CI_TAG_INHIBIT_CASCADE}"
   if is_this_tag_object_specified "${which_tag}" "${tag_name}"; then
     out_name="old_inhibit_cascade"
@@ -333,7 +456,7 @@ set_tag_locals_inhibit_cascade () {
 }
 
 set_tag_locals_inhibit_forever () {
-  # E.g., "ci-inhibit-forever"
+  # E.g., "ci-{branch}-inhibit-forever"
   tag_name="${EAPP_CI_TAG_INHIBIT_FOREVER}"
   if is_this_tag_object_specified "${which_tag}" "${tag_name}"; then
     out_name="old_inhibit_forever"
@@ -345,7 +468,7 @@ set_tag_locals_inhibit_forever () {
 }
 
 set_tag_locals_cascade_updatedeps () {
-  # E.g., "ci-cascade-updatedeps"
+  # E.g., "ci-{branch}-cascade-updatedeps"
   tag_name="${EAPP_CI_TAG_CASCADE_UPDATEDEPS}"
   if is_this_tag_object_specified "${which_tag}" "${tag_name}"; then
     out_name="old_cascade_updatedeps"
@@ -362,18 +485,38 @@ set_tag_locals_cascade_updatedeps () {
 #   the tag (and not create or delete it),
 #   or 'false' to remove the tag.
 set_tag_locals_cascade_versioning () {
-  # E.g., "ci-cascade-versioning"
+  # E.g., "ci-{branch}-cascade-versioning"
   tag_name="${EAPP_CI_TAG_CASCADE_VERSIONING}"
   if is_this_tag_object_specified "${which_tag}" "${tag_name}"; then
     out_name="old_cascade_versioning"
     tag_scope="HEAD"
-    # This particular default is not really important, because user has to
-    # choose from a dropdown to send workflow_event to initiate the cascade.
-    # - So this tag value should always be set.
-    # But we'll use 'alpha' to match update-merged.yml.
     default_value="skip"
     new_tag_value="${EAPP_CASCADE_VERSIONING}"
     delete_if=${EAPP_DELETE_CASCADE_VERSIONING:-false}
+  fi
+}
+
+set_tag_locals_inhibit_alpha () {
+  # E.g., "ci-inhibit-alpha"
+  tag_name="${EAPP_CI_TAG_INHIBIT_ALPHA}"
+  if is_this_tag_object_specified "${which_tag}" "${tag_name}"; then
+    out_name="old_inhibit_alpha"
+    tag_scope="project"
+    default_value="false"
+    new_tag_value="${EAPP_INHIBIT_ALPHA}"
+    delete_if=${EAPP_DELETE_INHIBIT_ALPHA:-false}
+  fi
+}
+
+set_tag_locals_inhibit_patch () {
+  # E.g., "ci-inhibit-patch"
+  tag_name="${EAPP_CI_TAG_INHIBIT_PATCH}"
+  if is_this_tag_object_specified "${which_tag}" "${tag_name}"; then
+    out_name="old_inhibit_patch"
+    tag_scope="project"
+    default_value="false"
+    new_tag_value="${EAPP_INHIBIT_PATCH}"
+    delete_if=${EAPP_DELETE_INHIBIT_PATCH:-false}
   fi
 }
 
@@ -396,10 +539,30 @@ trace_full () {
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
+_NORMAL_EXIT=false
+
+exit_1 () { _NORMAL_EXIT=true; exit 1; }
+
+exit_0 () { _NORMAL_EXIT=true; exit 0; }
+
+exit_cleanup () {
+  if ! ${_NORMAL_EXIT}; then
+    >&2 echo "GAFFE: ${PROG_NAME} exited abnormally!"
+    >&2 echo "- Hint: Enable \`set -x\` and run again..."
+  fi
+}
+
+# ***
+
 main () {
   set -e
 
+  trap exit_cleanup EXIT
+
   wrangle_tags "$@"
+
+  # Unhook exit_cleanup.
+  trap - EXIT
 }
 
 if [ "$0" = "${BASH_SOURCE[0]}" ]; then
diff --git a/.github/workflows/release-github.yml b/.github/workflows/release-github.yml
--- a/.github/workflows/release-github.yml
+++ b/.github/workflows/release-github.yml
@@ -69,17 +69,24 @@ jobs:
         shell: bash
 
       - name: Check if prerelease
+        id: check-if-prerelease
         # Note the v?: Don't care!
         run: |
-          echo "$VERSION_TAG" | grep -q -E -e "^v?[0-9]+\.[0-9]+\.[0-9]+$" \
-            || echo "PRERELEASE=--prerelease" >> "$GITHUB_ENV"
+          is_prerelease=false
+          if ! echo "${VERSION_TAG}" \
+            | grep -q -E -e "^v?[0-9]+\.[0-9]+\.[0-9]+$" \
+          ; then
+            is_prerelease=true
+            echo "PRERELEASE=--prerelease" >> "${GITHUB_ENV}"
+          fi
+          echo "is_prerelease=${is_prerelease}" >> "${GITHUB_OUTPUT}"
 
       - name: Announcement
         run: |
           [ -z "${PRERELEASE}" ] \
             && prerelease_msg="" \
             || prerelease_msg=" (prerelease)"
-          echo "Processing $VERSION_TAG tag${prerelease_msg}"
+          echo "Processing ${VERSION_TAG} tag${prerelease_msg}"
 
       # ***
 
@@ -92,14 +99,35 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
         with:
-          ref: ${{ github.event.repository.default_branch }}
+          # If pre-release, use alternative branch if defined.
+          ref: ${{
+            steps.check-if-prerelease.outputs.is_prerelease == 'true'
+            && vars.PRERELEASE_BRANCH
+            || github.event.repository.default_branch }}
           # Fetch all history, so rev-parse HEAD is real HEAD.
           fetch-depth: 0
 
-      # Compare default branch HEAD and workflow event GITHUB_SHA.
-      - name: Verify default branch HEAD is what was tagged
+      # Fail workflow unless workflow event GITHUB_SHA matches branch HEAD.
+      # - Note that, sure, the user might have pushed more commits to HEAD
+      #   since they version-tagged. So maybe that's a legit use case, and
+      #   this check is overkill. And maybe someday we'll disable this check.
+      #   - But until that day when this check actually annoys you, leave it.
+      - name: Verify branch HEAD is what was tagged
         run: |
-          [ "$GITHUB_SHA" = "$(git rev-parse HEAD)" ] || exit 1
+          echo "test \"${GITHUB_SHA}\" = \"$(git rev-parse HEAD)\""
+          [ "${GITHUB_SHA}" = "$(git rev-parse HEAD)" ] || exit 1
+
+      # Similar to last check, this might be overkill, but check the version
+      # exists on the HEAD commit, too.
+      - name: Verify branch HEAD is what was versioned
+        run: |
+          head_tag_match="$(git tag --list --points-at HEAD "${VERSION_TAG}")"
+          echo "test \"${head_tag_match}\" = \"${VERSION_TAG}\""
+          ([ -n "${head_tag_match}" ] \
+           && [ "${head_tag_match}" = "${VERSION_TAG}" ] \
+          ) || exit 1
+        env:
+          VERSION_TAG: ${{ inputs.version_tag }}
 
       # ***
 
diff --git a/.github/workflows/release-pypi.yml b/.github/workflows/release-pypi.yml
--- a/.github/workflows/release-pypi.yml
+++ b/.github/workflows/release-pypi.yml
@@ -111,29 +111,85 @@ jobs:
         uses: actions/checkout@v4
         with:
           ref: ${{ github.event.repository.default_branch }}
-          # Fetch all history, so rev-parse HEAD is real HEAD.
+          # Grab everything, because we might need to switch branches
+          # in the next step.
           fetch-depth: 0
         if: github.event_name == 'workflow_dispatch'
 
+      # Check the default branch HEAD for a version tag.
+      # - If it's not found, try the pre-release branch.
+      # - T_M_I: Note there are 2 branches that might be version-tagged:
+      #     the main, default branch; and
+      #     the 'liminal' (pre-release) branch.
+      #   - Within the main branch, if any commit has a pre-release version,
+      #     that commit *also* has a normal version.
+      #   - In the other, 'liminal', branch, it's the other way around: any
+      #     commit might only have a pre-release version, or nothing, but any
+      #     commit in the 'liminal' branch with a normal version also has a
+      #     pre-release version.
       - name: Probe version tag (is workflow_dispatch)
+        if: github.event_name == 'workflow_dispatch'
+        env:
+          PRERELEASE_BRANCH: ${{ vars.PRERELEASE_BRANCH }}
         run: |
-          version_tags="$(
+          print_version_tags () {
             git tag --list --points-at HEAD \
-              | grep -E -e "${VERSPARTS}" \
-          )"
+              | grep -E -e "${VERSPARTS}"
+          }
 
-          if $(echo "${version_tags}" | wc -l) -gt 1; then
-            >&2 echo "ERROR: Multiple version tags already"
+          branch_name="$(git rev-parse --abbrev-ref=loose HEAD)"
+
+          version_tags="$(print_version_tags)"
+
+          if [ -z "${version_tags}" ] && [ -n "${PRERELEASE_BRANCH}" ]; then
+            # Try the pre-release branch.
+            git checkout ${PRERELEASE_BRANCH}
+
+            branch_name="${PRERELEASE_BRANCH}"
+
+            version_tags="$(print_version_tags)"
+          fi
+
+          if [ -z "${version_tags}" ]; then
+            >&2 echo "ERROR: Nothing to do: HEAD(s) not versioned"
 
             exit 1
           fi
 
-          VERSION_TAG="${version_tags}"
+          echo "Version tag(s) on “${branch_name}”: ${version_tags}"
+
+          # If multiple versions tagged, choose the largest.
+          # - Note this is quite unnecessary, as this use case (a user
+          #   deliberately initiating release-pypi from the GitHub Actions
+          #   website, or via `gh workflow run`, notwithstanding there
+          #   being multiple versions on the latest commit) is both rare
+          #   and not at all critical. The majority, if not all, PyPI
+          #   releases will be due to the 'release' event, not workflow-D.
+          # Note that `sort -V|--version-sort` sorts pre-release before
+          # their normal counterparts, so it's sorta useless, and we'll
+          # just grab the "largest" 2 versions and then do a simple pre-
+          # release vs. normal comparison, knowing that, if the user is
+          # playing by the rules, there will only be at most 2 versions
+          # tagged.
+          if $(echo "${version_tags}" | wc -l) -lt 2; then
+            VERSION_TAG="${version_tags}"
+          else
+            possible_versions="$(echo "${version_tags}" | sort -V -r | head -2)"
+            possible_largest="$(echo "${possible_versions}" | head -1)"
+            other_possibility="$(echo "${possible_versions}" | tail -1)"
+
+            if [[ "${possible_largest}" =~ "${other_possibility}"* ]]; then
+              # Means ${possible_largest} is a pre-release of ${other_possibility},
+              # e.g., [[ 1.2.4-alpha.1 =~ 1.2.4* ]]
+              possible_largest="${other_possibility}"
+            fi
+
+            VERSION_TAG="${possible_largest}"
+          fi
 
           echo "VERSION_TAG=${VERSION_TAG} [${version_tags}]"
 
           echo "VERSION_TAG=${VERSION_TAG}" >> "${GITHUB_ENV}"
-        if: github.event_name == 'workflow_dispatch'
 
       # MEH: We could support HEAD not being tagged (e.g., user wants to
       # tag and release previous commit) if we looked instead for highest
@@ -180,13 +236,12 @@ jobs:
           [ -z "${extra_index_arg}" ] \
             && pipx_pip_args="" \
             || pipx_pip_args="--pip-args=${extra_index_arg}"
-          #
+
           ! ${PRERELEASE} \
             && index_url_pip="" \
             || index_url_pip="--index-url ${test_pypi_url} ${extra_index_arg}"
           echo "INDEX_PIP=${index_url_pip}" >> "${GITHUB_ENV}"
-          #
-          # yamllint disable-line rule:line-length
+
           ! ${PRERELEASE} \
             && index_url_pipx="" \
             || index_url_pipx="--index-url ${test_pypi_url} ${pipx_pip_args}"
@@ -217,9 +272,11 @@ jobs:
       # On GHA: pipx: error: unrecognized arguments: easy-as-pypi==1.1.1a20
       - name: Check if previously released
         run: |
-          echo "pipx install ${INDEX_PIPX} ${PACKAGE_NAME}==${VERSION}"
-          ! pipx install ${INDEX_PIPX} ${PACKAGE_NAME}==${VERSION} \
-            || echo "IS_RELEASED=true" >> "${GITHUB_ENV}"
+          IS_RELEASED=false
+          echo "pip install ${INDEX_PIP} ${PACKAGE_NAME}==${VERSION}"
+          pip install ${INDEX_PIP} ${PACKAGE_NAME}==${VERSION} \
+            && IS_RELEASED=true
+          echo "IS_RELEASED=${IS_RELEASED}" >> "${GITHUB_ENV}"
         shell: bash
 
       # Determine if previously released (and skip re-releasing if so).
@@ -247,15 +304,15 @@ jobs:
       #         gh release download ${VERSION_TAG} -D dist/
       #       env:
       #         GH_TOKEN: ${{ github.token }}
-      #       if: env.IS_RELEASED == ''
+      #       if: env.IS_RELEASED == 'false'
       #
       #     - name: Install poetry
       #       run: pipx install poetry
-      #       if: env.IS_RELEASED == ''
+      #       if: env.IS_RELEASED == 'false'
       #
       #     - name: Install poetry-dynamic-versioning
       #       run: poetry self add "poetry-dynamic-versioning[plugin]"
-      #       if: env.IS_RELEASED == ''
+      #       if: env.IS_RELEASED == 'false'
       #
       #     # CXREF: https://python-poetry.org/docs/repositories/
       #     - name: Poetry publish package
@@ -277,7 +334,7 @@ jobs:
       #         echo
       #         echo "poetry publish ${repository}"
       #         poetry publish ${repository}
-      #       if: env.IS_RELEASED == ''
+      #       if: env.IS_RELEASED == 'false'
 
       - name: Store variables for next job
         id: set_outputs
@@ -290,6 +347,9 @@ jobs:
           echo "VERSION=${VERSION}" >> "${GITHUB_OUTPUT}"
           echo "VERSION_TAG=${VERSION_TAG}" >> "${GITHUB_OUTPUT}"
 
+          echo "GITHUB_OUTPUT:"
+          cat "${GITHUB_OUTPUT}" | sed 's/^/  /'
+
     outputs:
       INDEX_PIP: ${{ steps.set_outputs.outputs.INDEX_PIP }}
       INDEX_PIPX: ${{ steps.set_outputs.outputs.INDEX_PIPX }}
@@ -301,20 +361,34 @@ jobs:
 
   # ***
 
+  wrangle-ci-tags:
+    name: Wrangle (read) CI tags
+    uses: ./.github/workflows/ci-tags-wrangle.yml
+    needs: [prepare-publish]
+    if: ${{ ! cancelled()
+      && needs.prepare-publish.result == 'success'
+      && needs.prepare-publish.outputs.IS_RELEASED == 'false' }}
+    with:
+      prerelease: ${{ needs.prepare-publish.outputs.PRERELEASE == 'true' }}
+
+  # ***
+
   poetry-publish:
 
     runs-on: ubuntu-latest
 
-    needs: prepare-publish
+    needs: [prepare-publish, wrangle-ci-tags]
 
     # Easiest approach would be to skip if IS_RELEASED, e.g.,
-    #   if: needs.prepare-publish.outputs.IS_RELEASED == '' && ...
+    #   if: needs.prepare-publish.outputs.IS_RELEASED == 'false' && ...
     # but if this job is skipped, so is smoke-test, which 'needs'
     # this job. So we'll skip the individual steps, and not the job.
     # - Unfortunately, pypa/gh-action-pypi-publish@release/v1 still builds
     #   its image, even when its step(s) skipped, which takes a few moments.
-    if: needs.prepare-publish.result == 'success'
-      && needs.prepare-publish.outputs.IS_RELEASED == ''
+    if: ${{ ! cancelled()
+      && needs.prepare-publish.result == 'success'
+      && needs.prepare-publish.outputs.IS_RELEASED == 'false'
+      && needs.wrangle-ci-tags.outputs.old-inhibit-release-pypi == 'false' }}
 
     # CXREF: PyPI recommends using an environment ('release')
     #        to keep non-admin organization members from publishing.
@@ -348,6 +422,8 @@ jobs:
     steps:
       - name: Checkout repository (for gh)
         uses: actions/checkout@v4
+        # Skip: No need to checkout ${{ vars.PRERELEASE_BRANCH }}
+        #       if pre-release; we just need repo for `gh` command.
 
       # Note that `gh status` does not work here, prints error:
       #   could not load notifications: could not get notifications:
@@ -387,21 +463,24 @@ jobs:
         uses: pypa/gh-action-pypi-publish@release/v1
         with:
           repository-url: https://test.pypi.org/legacy/
-        # Always publish to test.PyPI, so that "our" downstream deps always
-        # get the latest package version when they use the test.PyPI source
-        # (which is what happens on a pre-release cascade).
+        # Only publish pre-release packages to test.PyPI.
         #
-        # - Note that smoke-test only checks the release indicated by
-        #   env.PRERELEASE, because that's the only source that matters.
-        #
-        #   - E.g., we release normals to both test.PyPI and to PyPI, but
-        #     smoke-test only blocks repository_dispatch until the PyPI
-        #     package is alive, because that's all that downstreams need.
-        #
-        #     Likewise, because we release alphas only to test.PyPI,
-        #     smoke-test only blocks repository_dispatch until the
-        #     test.PyPI package is alive.
-        if: true
+        # - It's not prudent to publish normal packages to test.PyPI,
+        #   because the normal package was made from a normal build,
+        #   and the normal build only includes normal sources.
+        #   - That is, the `poetry build` was run on the main branch,
+        #     and its pyproject.toml uses deps from normal PyPI.
+        #     - And if we post such a project to test.PyPI, whose deps
+        #       might ref older versions than the current alpha deps,
+        #       I'd assume there'd be chayos. Maybe package versions
+        #       downgrading, or Poetry failing because deps conflicts,
+        #       I guess I'm not sure, but it smells like danger.
+        #   - And note that pip uses the first package index it finds
+        #     that has the source. I.e., pip *does not* search multiple
+        #     indices and pick the largest-version source.
+        # - So for either type or release cascade, whether 'alpha'
+        #   or 'patch', we always publish to the same package index.
+        if: env.PRERELEASE == 'true'
 
       - name: Publish package distributions to PyPI
         uses: pypa/gh-action-pypi-publish@release/v1
@@ -418,7 +497,7 @@ jobs:
 
     needs: [prepare-publish, poetry-publish]
 
-    # Note the 'if' is skipped if any needs were skipped, unless always.
+    # Note 'if' skipped if any needs skipped, unless always() or cancelled().
     if: ${{ ! cancelled()
       && needs.prepare-publish.result == 'success'
       && (needs.poetry-publish.result == 'success'
@@ -435,7 +514,7 @@ jobs:
       - name: Sleep for 13 seconds
         run: sleep 13s
         shell: bash
-        if: needs.prepare-publish.outputs.IS_RELEASED == ''
+        if: needs.prepare-publish.outputs.IS_RELEASED == 'false'
 
   # ***
 
@@ -459,6 +538,10 @@ jobs:
   #       same workflow. (I tried `pip cache remove ${PACKAGE_NAME}`,
   #       which removes nothing, because no wheels files downloaded,
   #       not surprising, but worth a shot.)
+  #
+  #     - REFER: This feels similar to `poetry cache clear PyPI --all`,
+  #       when `poetry update` doesn't see a new release, but Poetry
+  #       is not involved here.
 
   # - DUNNO/2023-10-08: I ran this workflow manually, and pipx-install
   #   installed the version. But then in the new workflow, pipx-install
@@ -472,14 +555,18 @@ jobs:
 
     needs: [prepare-publish, poetry-publish, sleep-before-smoking]
 
-    # Run if all needs 'success' or 'skipped'.
     if: ${{ ! cancelled()
       && !contains(needs.*.result, 'failure')
-      && !contains(needs.*.result, 'cancelled') }}
+      && (needs.poetry-publish.result == 'success'
+          || (needs.poetry-publish.result == 'skipped'
+              && needs.prepare-publish.outputs.IS_RELEASED == 'true'
+             )) }}
 
     steps:
-      - name: Checkout repository (not workflow_dispatch)
+      - name: Checkout repository
         uses: actions/checkout@v4
+        # Skip: No need to checkout ${{ vars.PRERELEASE_BRANCH }}
+        #       if pre-release; we just need repo for `gh` command.
 
       # # REFER: https://cli.github.com/manual/gh_workflow_run
       # - name: Re-run this workflow...
@@ -501,7 +588,8 @@ jobs:
             -f "INDEX_PIP=${INDEX_PIP}" \
             -f "INDEX_PIPX=${INDEX_PIPX}" \
             -f "PACKAGE_NAME=${PACKAGE_NAME}" \
-            -f "VERSION=${VERSION}"
+            -f "VERSION=${VERSION}" \
+            -f "PRERELEASE=${PRERELEASE}"
           #
           # echo "... | gh workflow run release-smoke-test.yml --json"
           # # Doesn't like double-quotes outside, singles inside:
@@ -526,5 +614,6 @@ jobs:
           INDEX_PIPX: ${{ needs.prepare-publish.outputs.INDEX_PIPX }}
           PACKAGE_NAME: ${{ needs.prepare-publish.outputs.PACKAGE_NAME }}
           VERSION: ${{ needs.prepare-publish.outputs.VERSION }}
+          PRERELEASE: ${{ needs.prepare-publish.outputs.PRERELEASE }}
 
 # ***
